StructType(
    List(
        StructField(cp,StringType,true),
        StructField(start,StringType,true),
        StructField(processedTime,StringType,true),
        StructField(type,StringType,true),
        StructField(id,StringType,true),
        StructField(geo,
                    StructType(
                        List(
                            StructField(city,StringType,true),
                            StructField(country,StringType,true),
                            StructField(lat,StringType,true),
                            StructField(region,StringType,true),
                            StructField(area,StringType,true),
                            StructField(zip,StringType,true),
                            StructField(long,StringType,true)
                            )
                        ),true),
        StructField(reqid,StringType,true),
        StructField(guid,StringType,true),
        StructField(message,
                    StructType(
                        List(
                            StructField(bytes,StringType,true),
                            StructField(cliIP,StringType,true),
                            StructField(fwdHost,StringType,true),
                            StructField(proto,StringType,true),
                            StructField(protoVer,StringType,true),
                            StructField(reqHost,StringType,true),
                            StructField(reqMethod,StringType,true),
                            StructField(reqPath,StringType,true),
                            StructField(reqPort,StringType,true),
                            StructField(respCT,StringType,true),
                            StructField(respLen,StringType,true),
                            StructField(status,StringType,true),
                            StructField(queryStr,StringType,true),
                            StructField(UA,StringType,true)
                            )
                        ),true),
        StructField(netPerf,
                    StructType(
                        List(
                            StructField(netOriginLatency,IntegerType,true),
                            StructField(downloadStatus,StringType,true),
                            StructField(clientRTT,IntegerType,true),
                            StructField(midMileLatency,IntegerType,true),
                            StructField(asnum,StringType,true),
                            StructField(downloadTime,StringType,true),
                            StructField(edgeIP,StringType,true),
                            StructField(lastByte,StringType,true),
                            StructField(errCdR14,StringType,true),
                            StructField(errCdF29,StringType,true)
                            )
                        ),true),
        StructField(cache,
                    StructType(
                        List(
                            StructField(cacheHit,StringType,true),
                            StructField(cacheable,StringType,true),
                            StructField(cacheStatus,StringType,true),
                            StructField(cacheStats,StringType,true),
                            StructField(cacheH,StringType,true)
                            )
                        ),true),
        StructField(waf,
                    StructType(
                        List(
                            StructField(riskScores,StringType,true),
                            StructField(pRate,IntegerType,true),
                            StructField(warnActions,StringType,true),
                            StructField(ver,StringType,true),
                            StructField(warnSlrs,StringType,true),
                            StructField(warnRules,StringType,true),
                            StructField(pAction,StringType,true),
                            StructField(riskGroups,StringType,true),
                            StructField(warnData,StringType,true),
                            StructField(denyActions,StringType,true),
                            StructField(denySlrs,StringType,true),
                            StructField(anomScr,StringType,true),
                            StructField(warnTags,StringType,true),
                            StructField(denyMsg,StringType,true),
                            StructField(riskTuples,StringType,true),
                            StructField(warnMsg,StringType,true),
                            StructField(policy,StringType,true),
                            StructField(denyRules,StringType,true),
                            StructField(denyData,StringType,true)
                            )
                        ),true),
        StructField(network,
                    StructType(
                        List(
                            StructField(nw,StringType,true),
                            StructField(nwType,StringType,true),
                            StructField(throughput,StringType,true),
                            StructField(proxy,StringType,true),
                            StructField(bw,StringType,true)
                            )
                        ),true),
        StructField(reqHdr,
                    StructType(
                        List(
                            StructField(cookie,StringType,true),
                            StructField(reqTime,StringType,true),
                            StructField(accEnc,StringType,true),
                            StructField(accLang,StringType,true),
                            StructField(auth,StringType,true),
                            StructField(reqCacheCtl,StringType,true),
                            StructField(reqConn,StringType,true),
                            StructField(reqContMD5,StringType,true),
                            StructField(DNT,StringType,true),
                            StructField(expect,StringType,true),
                            StructField(ifMatch,StringType,true),
                            StructField(ifMod,StringType,true),
                            StructField(ifNone,StringType,true),
                            StructField(ifRange,StringType,true),
                            StructField(ifUnmod,StringType,true),
                            StructField(range,StringType,true),
                            StructField(referer,StringType,true),
                            StructField(te,StringType,true),
                            StructField(upgrade,StringType,true),
                            StructField(reqVia,StringType,true),
                            StructField(xFrwdFor,StringType,true),
                            StructField(xReqWith,StringType,true)
                            )
                        ),true),
        StructField(respHdr,
                    StructType(
                        List(
                            StructField(accRange,StringType,true),
                            StructField(respCacheCtl,StringType,true),
                            StructField(respConn,StringType,true),
                            StructField(respContMD5,StringType,true),
                            StructField(respVia,StringType,true),
                            StructField(allowOrigin,StringType,true),
                            StructField(age,StringType,true),
                            StructField(allow,StringType,true),
                            StructField(contEnc,StringType,true),
                            StructField(contLang,StringType,true),
                            StructField(contDisp,StringType,true),
                            StructField(contRange,StringType,true),
                            StructField(expires,StringType,true),
                            StructField(link,StringType,true),
                            StructField(p3p,StringType,true),
                            StructField(retry,StringType,true),
                            StructField(trailer,StringType,true),
                            StructField(transEnc,StringType,true),
                            StructField(vary,StringType,true),
                            StructField(warning,StringType,true),
                            StructField(wwwAuth,StringType,true),
                            StructField(setCookie,StringType,true),
                            StructField(date,StringType,true),
                            StructField(eTag,StringType,true),
                            StructField(lastMod,StringType,true),
                            StructField(server,StringType,true),
                            StructField(xPwrdBy,StringType,true)
                            )
                        ),true)
        )
    )
