itm_nfs_vnd_mcr ok
vnd_crt_fma_pgt ok
vnd_mtg_fma_pgt ok
inf_cec_ped_cno ok
tip_pub_loj_fil ok
set_mcr_agp_set ok
inf_rlc_cec_cno ok
tip_psc_pve_mcr ok
itm_vnd_crt_prs ok
agp_vrs_fil_mcr ok
psc_stc_trc_dev ok
vnd_srv_fma_pgt ok 
pve_mcr_fma_pgt ok 
stc_trc_dev ok 
atn_pto_atv ok 
sec_mcr_loj ok 
ped_itl_mtg ok 
cla_esp_mcr ok 
pve_mcr_mtg ok 
inf_cpm_cli ok 
tip_pub_loj ok 
agp_ger_rga ok 
itm_fol_trb ok 
mov_rcb_bco ok 
itm_vnd_mtg ok 
pve_trc_dev ok 
vnd_crt_prs ok 
agp_mcr_anc ok 
mot_irr_pve ok  
tip_agp_rga ok 
inf_ped_cno ok 
nfe_ret_etg ok 
set_mcr ok 
vnd_srv ok 
vnd_mtg ok 
pdt_mcr ok 
esp_mcr ok 
rsr_mcr ok 
mrc_mcr ok 
lgr_ect ok 
ctt_cli ok 
trk_uni ok 
rot_etg ok 
mic_zen ok 
cla_mcr ok 
cga_etg ok 
cto_cli ok 
cli ok 
fne ok 
bnd ok 
mun ok 